language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t ansible .
  - docker run -it --name ansible ansible

script:
  - ansible --version
  - pip show pyvmomi
  - pip show ovirt-engine-sdk-python
